<?php

const CERTIFICATE_DIRECTORY = __DIR__ . DIRECTORY_SEPARATOR . "apache2" . DIRECTORY_SEPARATOR . "certificates";
const ANDROID_DIRECTORY = __DIR__ . DIRECTORY_SEPARATOR . "android";
const APP_DIRECTORY = ANDROID_DIRECTORY . DIRECTORY_SEPARATOR . "app";
const APP_RAW_DIRECTORY = APP_DIRECTORY . DIRECTORY_SEPARATOR . "src" . DIRECTORY_SEPARATOR . "main" . DIRECTORY_SEPARATOR . "res" . DIRECTORY_SEPARATOR . "raw";

const APACHE_KEY_FILE = CERTIFICATE_DIRECTORY . DIRECTORY_SEPARATOR . "out.key";
const APACHE_CRT_FILE = CERTIFICATE_DIRECTORY . DIRECTORY_SEPARATOR . "out.crt";
const APP_CRT_FILE = APP_RAW_DIRECTORY . DIRECTORY_SEPARATOR . "certificate.crt";
const APP_JSON_FILE = APP_RAW_DIRECTORY . DIRECTORY_SEPARATOR . "app.json";

const APP_KEYSTORE = ANDROID_DIRECTORY . DIRECTORY_SEPARATOR . "keystore.jks";
const APP_APK = APP_DIRECTORY . DIRECTORY_SEPARATOR . "build" . DIRECTORY_SEPARATOR . "outputs" . DIRECTORY_SEPARATOR . "apk" . DIRECTORY_SEPARATOR . "release" . DIRECTORY_SEPARATOR . "app-release.apk";

const WEB_APK = __DIR__ . DIRECTORY_SEPARATOR . "web" . DIRECTORY_SEPARATOR . "files" . DIRECTORY_SEPARATOR . "public" . DIRECTORY_SEPARATOR . "foobar.apk";
const WEB_JSON_FILE = __DIR__ . DIRECTORY_SEPARATOR . "web" . DIRECTORY_SEPARATOR . "files" . DIRECTORY_SEPARATOR . "private" . DIRECTORY_SEPARATOR . "databases" . DIRECTORY_SEPARATOR . "app.json";
